import type { Scene } from "../../graph/scene";
import { Component } from "../component.js";
import { TransformComponent } from "./transform.js";
export declare type CameraType = "orthographic" | "perspective";
export declare class CameraComponent extends Component {
    transform: TransformComponent;
    mounted(): void;
    private _type;
    get type(): CameraType;
    private _projectionMatrixDirty;
    private projectionMatrix;
    private _viewProjectionMatrix;
    get viewProjectionMatrix(): Float32Array;
    private _fieldOfView;
    get fieldOfView(): number;
    set fieldOfView(v: number);
    private _aspect;
    get aspect(): number;
    set aspect(v: number);
    private _near;
    get near(): number;
    set near(v: number);
    private _far;
    get far(): number;
    set far(v: number);
    private _left;
    get left(): number;
    set left(v: number);
    private _right;
    get right(): number;
    set right(v: number);
    private _top;
    get top(): number;
    set top(v: number);
    private _bottom;
    get bottom(): number;
    set bottom(v: number);
    setPerspective(fov: number, aspect: number, near: number, far: number): this;
    setOrthographic(left: number, right: number, top: number, bottom: number, near: number, far: number): this;
    constructor();
    update(scene: Scene): void;
}
